# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SiKataster
                                 A QGIS plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-12
        copyright            : (C) 2024 by Matjaž Mori
        email                : matjaz.mori@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""



import pkg_resources
import subprocess
from PyQt5.QtWidgets import QMessageBox
from qgis.utils import iface

def check_and_install_packages():
    # Define the required packages and their upgrade requirements
    install_requires = ['keyring', 'selenium']

    # Flag to track if any package was installed or upgraded
    changes_made = False

    # Install required packages
    for package in install_requires:
        if install_package(package):
            changes_made = True

    # Show restart message if any changes were made
    if changes_made:
        show_restart_message()

def install_package(package):
    changes_made = False
    try:
        pkg_resources.get_distribution(package)
    except pkg_resources.DistributionNotFound:
        subprocess.check_call(['python', '-m', 'pip', 'install', package])
        changes_made = True
    return changes_made

def show_restart_message():
    msg = QMessageBox()
    msg.setIcon(QMessageBox.Information)
    msg.setText("QGIS needs to be restarted for installation changes to take effect.")
    msg.setWindowTitle("SiKataster")
    msg.setStandardButtons(QMessageBox.Ok)
    msg.exec_()

# Check and install packages when the plugin is loaded
check_and_install_packages()


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SiKataster class from file si_kataster.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .si_kataster import SiKataster
    return SiKataster(iface)
