# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SiKataster
                                 A QGIS plugin

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-11-12
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Matjaž Mori
        email                : matjaz.mori@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox

from qgis.core import QgsMessageLog, Qgis

from .resources import *

from .si_kataster_dockwidget import SiKatasterDockWidget
import os.path
import pkg_resources
import subprocess


def check_and_install_packages():
    # Define the required packages and their upgrade requirements
    install_requires = ['keyring', 'selenium']

    # Flag to track if any package was installed or upgraded
    changes_made = False

    # Install required packages
    for package in install_requires:
        if install_package(package):
            changes_made = True

    # Show restart message if any changes were made
    if changes_made:
        show_restart_message()

def install_package(package):
    changes_made = False
    try:
        pkg_resources.get_distribution(package)
    except pkg_resources.DistributionNotFound:
        subprocess.check_call(['python', '-m', 'pip', 'install', package])
        changes_made = True
    return changes_made

def show_restart_message():
    msg = QMessageBox()
    msg.setIcon(QMessageBox.Information)
    msg.setText(QCoreApplication.translate('SiKataster', 
        "QGIS mora biti ponovno zagnan, da se spremembe uveljavijo."))
    msg.setWindowTitle("SiKataster")
    msg.setStandardButtons(QMessageBox.Ok)
    msg.exec_()


class SiKataster:
    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        check_and_install_packages()
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)

        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'SiKataster_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr(u'&SiKataster')
        self.toolbar = self.iface.addToolBar(u'SiKataster')
        self.toolbar.setObjectName(u'SiKataster')

        self.pluginIsActive = False
        self.dockwidget = None
        
        self.web_session = None
        # Initialize web session if credentials exist
        self._initialize_web_session_if_ready()


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('SiKataster', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToWebMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action


    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        icon_path = os.path.join(
            self.plugin_dir, 'icon.png')
       
     
        self.add_action(
            icon_path,
            text=self.tr(u'SiKataster'),
            callback=self.run,
            parent=self.iface.mainWindow())

    #--------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""

        # disconnects
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)

        self.pluginIsActive = False


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        for action in self.actions:
            self.iface.removePluginWebMenu(
                self.tr(u'&SiKataster'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar
        
        # Clean up web session
        try:
            from .si_kataster_2web import EsodstvoWebClient
            EsodstvoWebClient.close_shared_session()
            QgsMessageLog.logMessage(
                self.tr("Spletna seja zaprta"),
                "SiKataster",
                Qgis.Info
            )
        except Exception as e:
            QgsMessageLog.logMessage(
                self.tr(f"Napaka pri zapiranju seje: {str(e)}"),
                "SiKataster",
                Qgis.Warning
            )

    #--------------------------------------------------------------------------

    def run(self):
        """Run method that loads and starts the plugin"""

        if not self.pluginIsActive:
            self.pluginIsActive = True

            # dockwidget may not exist if:
            #    first run of plugin
            #    removed on close (see self.onClosePlugin method)
            if self.dockwidget == None:
                # Create the dockwidget (after translation) and keep reference
                self.dockwidget = SiKatasterDockWidget()

            # connect to provide cleanup on closing of dockwidget
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)

            # show the dockwidget
            # TODO: fix to allow choice of dock location
            self.iface.addDockWidget(Qt.LeftDockWidgetArea, self.dockwidget)
            self.dockwidget.show()


    # --------------------------------------------------------------------------
    def _initialize_web_session_if_ready(self):
        """Initialize web session if valid credentials are stored"""
        try:
            # Get stored credentials
            username = keyring.get_password("SiKataster", "esodstvo_username")
            password = keyring.get_password("SiKataster", "esodstvo_password")
            
            if username and password:
                QgsMessageLog.logMessage(
                    self.tr("Najdene shranjene poverilnice, inicializacija spletne seje v ozadju..."),
                    "SiKataster",
                    Qgis.Info
                )
                
                # Start initialization in a background thread to not block QGIS startup
                from qgis.core import QgsTask, QgsApplication
                
                class InitSessionTask(QgsTask):
                    def __init__(self, username, password):
                        super().__init__('Initialize e-Sodstvo session', QgsTask.CanCancel)
                        self.username = username
                        self.password = password
                        self.exception = None
                    
                    def run(self):
                        try:
                            from .si_kataster_2web import EsodstvoWebClient
                            
                            QgsMessageLog.logMessage(
                                self.tr("Inicializacija ozadja: Ustvarjam spletnega odjemalca..."),
                                "SiKataster",
                                Qgis.Info
                            )
                            
                            # This will create and cache the browser session
                            client = EsodstvoWebClient(
                                self.username, 
                                self.password, 
                                headless=True, 
                                reuse_session=True
                            )
                            
                            QgsMessageLog.logMessage(
                                self.tr("Inicializacija ozadja: Prijavljanje..."),
                                "SiKataster",
                                Qgis.Info
                            )
                            
                            if not client.login():
                                self.exception = self.tr("Prijava neuspešna - neveljavne poverilnice")
                                # Clear invalid credentials
                                keyring.delete_password("SiKataster", "esodstvo_username")
                                keyring.delete_password("SiKataster", "esodstvo_password")
                                return False
                            
                            # Check status after login
                            status = EsodstvoWebClient.get_session_status()
                            QgsMessageLog.logMessage(
                                self.tr(f"Inicializacija ozadja: Po prijavi - {status}"),
                                "SiKataster",
                                Qgis.Info
                            )
                            
                            QgsMessageLog.logMessage(
                                self.tr("Inicializacija ozadja: Izbiranje vloge..."),
                                "SiKataster",
                                Qgis.Info
                            )
                            
                            if not client.select_land_registry_role():
                                status = EsodstvoWebClient.get_session_status()
                                self.exception = self.tr(f"Izbira vloge neuspešna. Status: {status}")
                                return False
                            
                            # Log final status
                            status = EsodstvoWebClient.get_session_status()
                            QgsMessageLog.logMessage(
                                self.tr(f"Inicializacija ozadja: Končano - {status}"),
                                "SiKataster",
                                Qgis.Success
                            )
                            
                            # Don't close the client - we want to keep the session
                            return True
                        except Exception as e:
                            import traceback
                            self.exception = traceback.format_exc()
                            QgsMessageLog.logMessage(
                                self.tr(f"Izjema pri inicializaciji ozadja: {self.exception}"),
                                "SiKataster",
                                Qgis.Critical
                            )
                            return False
                    
                    def finished(self, result):
                        if result:
                            QgsMessageLog.logMessage(
                                self.tr("✅ Seja e-sodstva pripravljena - prenosi PDF bodo hitri"),
                                "SiKataster",
                                Qgis.Success
                            )
                        else:
                            QgsMessageLog.logMessage(
                                self.tr(f"⚠️ Inicializacija ozadja neuspešna: {self.exception}. Seja bo ustvarjena ob prvi uporabi."),
                                "SiKataster",
                                Qgis.Warning
                            )
                
                # Start the initialization task
                task = InitSessionTask(username, password)
                QgsApplication.taskManager().addTask(task)
                
        except Exception as e:
            # Silently fail - session will be created on first use
            QgsMessageLog.logMessage(
                self.tr(f"Seja ni mogla biti pred-inicializirana: {str(e)}"),
                "SiKataster",
                Qgis.Warning
            )
